version: '3.8'
services:
  academic-service:
    build: ./academic-service
    restart: always
    # No exponemos puertos al exterior, queda aislado en la red interna de Docker

  attendance-service:
    build: ./attendance-service
    restart: always

  communication-service:
    build: ./communication-service
    restart: always

  bff-service:
    build: ./bff-service
    restart: always
    ports:
      - "9090:9090" # Solo el BFF es accesible desde la IP de la EC2
    environment:
      # Sobreescribimos el application.properties para usar la red interna de Docker
      - services.academic.url=http://academic-service:8081
      - services.attendance.url=http://attendance-service:8082
      - services.communication.url=http://communication-service:8083
    depends_on:
      - academic-service
      - attendance-service
      - communication-service